### ISSUE TITLE
Saving and restoring simulation state

### ISSUE THREAD

**Issue by rsholmes** [gemc/source#112]
For many purposes it can be useful to be able to re-run the simulation for a small subset of events. For example, you might have a large number of simulated events out of which there are ten which you'd like to examine visualization of, or which you'd like to re-run with mother saving turned on. 

For SoLID at one time (several years ago) I had a kludged version of this working. There were command line options to save the simulation state to a file, and to re-run the simulation for only the events whose state had been saved. The way saving worked was that before each event it would internally store the state of the RNG and (if any) the current input file data. During the event, the hit processor could call a routine called "SaveMe". After the event, if "SaveMe" had been called, the RNG and input data would be written to their own output files. To replay, if the command line option specified it, the RNG would be set on each event from the next saved state and the primary generator would be initialized from the next saved input data.

This worked for my purposes but was rather a kludge, since if you wanted to change the criteria for saving events you had to change the hit processor code and recompile.

Two ways to avoid that problem would be: (1) Provide a way to specify a selection criterion as an input, rather than hard coding it, or (2) Save the RNG for _all_ events, say in the header bank or in its own new bank; then to replay, specify numerically which events should be re-read from the input file and have the RNG set from the stored information in the output file. 

These have obvious drawbacks: (1) would require a parser similar to what ROOT uses for tree selection, a major piece of work. (2) requires adding, I believe, 625 unsigneds (the size of the RNG state) to the output for every event (if requested), a high storage price to pay. It may be the best way to do this, though. One presumably would use this option infrequently and not on enormous data sets, and 625 unsigneds per event would typically not be a large fractional increase in the size.

However, it would then be necessary to provide the capability for GEMC to read its own output files, potentially another can of worms.

**Comment by rsholmes** [comment]
Could the selection be done in a plugin?

**Comment by maureeungaro** [comment]
The state should be saved if requested - perhaps even by default. 

In gemc 2.X a selection criteria has been introduced in the digitization - and that’s a plug-in for 3.0. Now, that’s specific to sensitive detectors, but a similar mechanism could be thought for event action.

**Comment by maureeungaro** [comment]
Addressed with Richard own work and the option SAVE_SELECTED
