### ISSUE TITLE
put some field property back in map

### ISSUE THREAD

**Issue by zhaozhiwen** [gemc/source#147]
It seems minStep,integration,shift are not supported in map file file any more. They are simply ignored if defined in a map file
All of them have to be set in option.
This break backward compatibility at least from v2.3 when they are not ignored in map files.
And this can make gcard file unnecessary long

I would suggest to keep support of minStep,integration,shift, and add rotation in map files.
Then make options to override whatever defined in map.
This would restore backward compatibility and provide most flexibility.

I can try to implement them. Let me know.

**Comment by maureeungaro** [comment]
The minimum step, integration method, shift is not a map property. It is a run-time property, different simulation may be run with different values of these. 

It was actually a mistake in the first place to put it there, and it's also confusing. 

Please update to the latest gemc to use the best version. If you want to use an older version of gemc where the attributes are defined in the map file, you can put back these attributes in the files.

**Comment by zhaozhiwen** [comment]
hmm, 
I think at least shift and rotation are basic map property.
practically, a map is always defined at origin with max symmetry to  save size. Then it will be placed at the correct place by shift and rotation.
minimum step, integration method and interpolation are also common for a simulation wants to have default values which can be defined in map.
run time options are good when tuning those values, but not good for defining default values.
for example, eic simulation would need about 50 lines in gcard to define those basic map property which is a problem because it requires gcard file being part of simulation setup and it shouldn't not be.

**Comment by zhaozhiwen** [comment]
hmm,
I think at least shift and rotation are basic map property.
practically, a map is always defined at origin with max symmetry to save size. Then it will be placed at the correct place by shift and rotation.
minimum step, integration method and interpolation are also common for a simulation wants to have default values which can be defined in map.
run time options are good when tuning those values, but not good for defining default values.
for example, eic simulation would need about 50 lines in gcard to define those basic map property which is a problem because it requires gcard file being part of simulation setup and it shouldn't not be.

**Comment by zhaozhiwen** [comment]
hmm,
I think at least shift and rotation are basic map property.
practically, a map is always defined at origin with max symmetry to save size. Then it will be placed at the correct place by shift and rotation.
minimum step, integration method and interpolation are also common for a simulation wants to have default values which can be defined in map.
run time options are good when tuning those values, but not good for defining default values.
for example, eic simulation would need about 50 lines in gcard to define those basic map property which is a problem because it requires gcard file being part of simulation setup and it shouldn't not be.
