### ISSUE TITLE
New G4MultiSensitiveDetector

### ISSUE THREAD

**Issue by whit2333** [gemc/source#18]
I recommend using this for every sensitive logical volume. This would allow for more flexible hit processing and output.
 
From http://geant4.cern.ch/support/ReleaseNotes4.10.2.html
> Digitization & Hits
> Added new G4MultiSensitiveDetector functionality, allowing to assign multiple sensitive-detectors to a single logical-volume. Sensitive-detectors are added to this proxy class and an instance of the proxy is assigned to the logical volume. Calls to the sensitive-detectors methods are forwarded to all user-defined sensitive-detectors that are added.

**Comment by maureeungaro** [comment]
This functionality will be supported with the hit process plugins - where the detector variation will be associated with digitization routines.
