### ISSUE TITLE
hadronicPhys == "none"

### ISSUE THREAD

**Issue by zhaozhiwen** [gemc/source#207]
It used to be that hadronicPhys == "none" is ok in source/physics/PhysicsList.cc  
but this feature is gone.

Can it be added back by "else if(hadronicPhys == "none")            {;}" at line 374 ? 

and why some hadron list are commented out?

**Comment by zhaozhiwen** [comment]
It would be nice to have this feature

**Comment by maureeungaro** [comment]
This is added now, thanks!
