### ISSUE TITLE
reduce field map mem use by changing double to float

### ISSUE THREAD

**Issue by zhaozhiwen** [gemc/source#230]
magnetic field maps usually don't need precision of double type
The mem due to large field map can be reduced by almost 40%-60% after changing from double to float
The change is needed for fields/symmetries/*.cc, fields/mappedField.h
refer to https://github.com/JeffersonLab/solid_gemc/tree/master/mod/gemc/2.9/fields

**Comment by maureeungaro** [comment]
This was [addressed](https://github.com/gemc/source/commit/da3f5e4c64d1e1f8608aa735a425db427db0c23c).
