### ISSUE TITLE
make internal particle gun shoot evenly in solid angle

### ISSUE THREAD

**Issue by zhaozhiwen** [gemc/source#30]
Currently the internal particle gun doesn't shoot evenly in solid angle, it would be nice to do so

this will do the trick
change this line in  src/MPrimaryGeneratorAction.cc
Theta = stheta/rad + (2.0*G4UniformRand()-1.0)*dtheta/rad;
to
Theta = acos(G4UniformRand()*(cos(theta/rad-dtheta/rad)-cos(theta/rad+dtheta/rad))+cos(theta/rad+dtheta/rad))/rad;

will need to check if this works with option ALIGN_ZAXIS

**Comment by maureeungaro** [comment]
This can be done by default, and add an option SPREAD="flat" to do it the original way, would that work?

**Comment by zhaozhiwen** [comment]
Sure, 
Just curious why the original way?  I thought phasespace is what we want to call flat.

Sent by MailWise – See your emails as clean, short chats.

-------- Original Message --------

**Comment by maureeungaro** [comment]
An oversight probably.

**Comment by zhaozhiwen** [comment]
Maybe just change default as flat then, no need for new option then

Sent by MailWise – See your emails as clean, short chats.

**Comment by maureeungaro** [comment]
default is cos theta flat now. If the word "flat" is present after the 3 SPREAD parameters, then it's going to be theta flat instead
