### ISSUE TITLE
helium3Gas defination

### ISSUE THREAD

**Issue by zhaozhiwen** [gemc/source#48]
in file "source/materials/material_factory.cc"

	// helium 3 material gas
	// Density at 21.1Â°C (70Â°F) : 0.1650 kg/m3
	mats["helium3Gas"] = new G4Material("helium3Gas",  0.1650*mg/cm3, 1, kStateGas, 294.25*kelvin);
	mats["helium3Gas"]->AddElement(helium3, 1);

The density seems a bit large
0.932*44.6(amg=mol/m3)*3.016(g/mol)=1.254e-3g/cm3

refer to
https://en.wikipedia.org/wiki/Amagat

**Comment by maureeungaro** [comment]
This matches:

http://www.helium-3.com/description.html

**Comment by zhaozhiwen** [comment]
not sure why this reference give a large value, can it be at different pressure?

another reference gives result similar to calculation
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwiNoonApuTNAhWC9x4KHfMSDfMQFggqMAE&url=http%3A%2F%2Fwww.lindepremiumproducts.com%2Finternet.lg.lsg.usa%2Fen%2Fimages%2Fhe3-helium-3892_88295.pdf&usg=AFQjCNEpGtZIirblWtJaAQdV3vzW5NJw4g&sig2=AQRpHwTuZ6NPzTcG1sXgzg&cad=rja

It doesn't really matter, as user can redefine density in external material.
