### ISSUE TITLE
Unspecified number of events for LUND file

### ISSUE THREAD

**Issue by jrhosk** [gemc/source#60]
I would like to request the option to not specify the number of simulated event in a LUND file. The LUND file could be loaded as usual and events would be simulated until the EOF is reached. This would be very helpful in the event you are given a generator LUND file and the total number of events is not specified.
Thanks!

**Comment by maureeungaro** [comment]
N is now not necessary for an input file (such as LUND) if in batch mode. In interactive mode N is still necessary.
