### ISSUE TITLE
Generate an ion primary particle

### ISSUE THREAD

**Issue by jsgeorge68** [gemc/source#63]
I would like to be able to generate a specific ion (Fe-56 or C-12 or whatever) as a primary particle in gemc.  There is a GenericIon in the particle list but need to select what ion.
I have tried to set the ion in the G4dialog tab using:
/gun/particle ion
/gun/ion 26 56 2
/gun/position 0 0 2 cm
/gun/direction 0 0 -1
/gun/energy 1 GeV
/run/beamOn 1

I may not have the verbosity set right but have seen no indication that any message was reported with any of these commands.  However, if I forget to set '/gun/particle ion' first I do get an error message when I try '/gun/ion 26 56 2'.  I've also tried it without the '2' charge state.  Same result if I use the gemc 'Run' button after setting these instead of '/run/beamOn 1'.

I tried this again but setting the main particle to GenericIon in the gemc drop down menu.  I do see messages showing the particle changed to GenericIon in the output but nothing further when I try to set the ion using then G4dialog commands.

I'm using a simple time-of-flight as an example and for a fixed energy, the times between detector hits do not appear to change depending on what mass ion I'm trying to set.

**Comment by maureeungaro** [comment]
This issues has been addressed by using a new option "ION_P". 

For details:

https://gemc.jlab.org/gemc/html/documentation/generator/ion.html
