### ISSUE TITLE
feature, smart number of event

### ISSUE THREAD

**Issue by zhaozhiwen** [gemc/source#69]
Currently -N=100 will run 100 events even when input file only has 50 events
another feature  would be nice
When using input file, gemc don't need -N option and it can will run all events in the input by default
Add N option only if you want run number of events smaller than input file.
It will never run number of events larger than input file

**Comment by maureeungaro** [comment]
Both of these requests are now in gemc:

- if N is larger than the # events in the file, gemc will stop at the end of the file
- if N is not given, and we are in batch mode reading a file, then gemc will run through all the events in the file.
- In interactive mode N is still necessary.
