### ISSUE TITLE
BEAM_E and SPREAD_E options

### ISSUE THREAD

**Issue by jsgeorge68** [gemc/source#80]
Can we add an option to gemc to define the primary particle by kinetic energy instead of momentum?  And specify the spread in energy as well.  This would be a great help for the momentum-impaired.

Would also like to be able to specify an input spectrum to select the primary from but this would be taken care of if the general particle source is fully implemented so that feature can wait for the GPS.

**Comment by maureeungaro** [comment]
An optional argument can now be appended to BEAM_P: if "KE" is appended, then both BEAM_P and SPREAD_P will interpret the energy as kinematic energy, not momentum.

  For example, to simulate a K=250 MeV proton::

   -BEAM_P="proton, 250*MeV, 90*deg, 90*deg, KE"
