### ISSUE TITLE
Sensitive detector type to count number of photons (gflux)

### ISSUE THREAD

**Issue by jsgeorge68** [gemc/source#86]
I could really use the "gflux" sensitive detector type we've discussed that would count numbers of particles entering the volume without need to track in the volume.  This would be used for something like a PMT or SiPM where there may be many thousands of optical photons arriving at different points and directions but all I care about is how many were detected. It should be general for all particles, though, not just for optical photons.

A variation on this would be to save the time structure, for example, numbers of photons vs. time in the event.  This might be done by treating Nphoton vs time like a voltage waveform and then reading it out through the same way as the FADC.  Just one possibility.  The benefit would be for something like a scintillator with a Cerenkov component - one could sample the fast and slow components without having to save hundreds or thousands of hits, in some cases.  Or is there a better way to do that?

**Comment by maureeungaro** [comment]
A new detector type "counter" provide counts for all the most common particles: gammas, e+ e-, pions and kaons, protons and neutrons.
