### ISSUE TITLE
option to shift and rotate field 

### ISSUE THREAD

**Issue by zhaozhiwen** [gemc/source#91]
It would be nice to have the option to shift and rotate field.  This allow simple field map in some cases

**Comment by zhaozhiwen** [comment]
The geometry and field rotation have opposite sign

for example,  those two following things are need to make the correct rotation
eBDS61_iron | root | eBDS61_iron | -0.029998*m 0.0*m -34.49102238*m | 0*rad 0.02*rad 0*rad | 00FF00 | Box | 11.0*cm 11.0*cm 1.5*m | Kryptonite | eBDS61_map | 1 | 1 | 1 | 1 | 1 | no | no | no 
<option name="ROTATE_FIELDMAP" value="eBDS61_map, 0*rad, -0.02*rad, 0*rad"/> 

I am not totally sure which one is wrong. my guess is that field rotation is to blame

**Comment by maureeungaro** [comment]
Addressed with the options: DISPLACE_FIELDMAP and ROTATE_FIELDMAP
